name = "CoordinatePartitioning"
uuid = "32fe8c4e-b672-4382-8d7d-6d6a4010fa6e"
authors = ["sandyspiers <sandy.spiers@curtin.edu.au> and contributors"]
version = "1.0.0-DEV"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
