name = "CoordinatePartitioning"
uuid = "32fe8c4e-b672-4382-8d7d-6d6a4010fa6e"
authors = ["sandyspiers <sandy.spiers@curtin.edu.au> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
